---
      - name: Install python-pip | Debian
        apt: name=python-pip state=present
        when: ansible_os_family|lower == 'debian'

      - name: Install python-pip | RedHat
        yum: name=python-pip state=present
        when: ansible_os_family|lower == 'redhat'


      - name: Install elasticsearch-curator
        pip:
                name: elasticsearch-curator
                version: "{{ elasticsearch_curator_version }}"
                state: present

